### ISSUE TITLE
User account

### ISSUE THREAD

**Issue by nicolas-bastien** [smartbooster/sandbox#3]
Implement user profile

## Tasks

- [x] Add link in sidebar under name
- [x] Add link in user block in the main navigation
- [x] Add the user profile form
